### ISSUE TITLE
Decide on best way to describe data types for our content models

### ISSUE THREAD

**Issue by chachasikes** [cagov/design-system#223]
For our component documentation sessions, we added a Content Model section. 
This information helps developers understand what the expected content format is for a component, this helps with communicating limits defined from Content advisors, and with programming editor UIs, potentially in a variety of systems.

The structure is currently this:
`Field name | Data type | Notes`

In working though this, there are a few specs of data types & slight differences between them. We probably need to define these  a little bit. Current information is based off Contentful, TypeScript and Airtable. Microsoft has their own definitions. We are also using JSDocs and custom elements manifests. 

For example, it's helpful to know that the Title field for an accordion is Rich Text (any markup), but also to specific that the data type is Rich Text, but the allowed markup might be limited to bold, italic, and maybe a link. Knowing this can help CMS developer to work faster and with less errors or confusion. 

* We also might want the character count limit.

Let's sort this out in this thread.

## References
Content Model are well known in content strategy and for CMS developers.
Here are some articles defining  content models.
https://graphcms.com/academy/what-is-content-modeling
https://www.contentstack.com/blog/all-about-headless/content-modeling-and-headless-cms/
https://thecontentwrangler.com/glossary/content-model/
https://www.uxbooth.com/articles/complete-beginners-guide-to-content-strategy/

**Comment by chachasikes** [comment]
@xjensen @zakiya  tagging you both on this thread because we've either discussed content modeling or data types.

My next steps: 
Add some references and examples to allow us to decide which format makes sense for the design system.

**Comment by chachasikes** [comment]
We also use JSON schema.

**Comment by chachasikes** [comment]
Some readily available examples
*  (.net): https://docs.microsoft.com/en-us/windows/win32/wmp/about--net-framework-data-types (I'm not a .net dev, so not the best person to ask about what a good recent example would be) 
* Airtable: https://support.airtable.com/hc/en-us/articles/360055885353-Field-types-reference
* Contentful: https://www.contentful.com/developers/docs/concepts/data-model/

**Comment by chachasikes** [comment]
General to JS implementations (wouldn't have richtext, richtext is a string)
* JSDocs https://jsdoc.app/tags-property.html (more general)
* JSON Schema https://json-schema.org/draft/2020-12/json-schema-core.html#rfc.section.4.3.1

**Comment by chachasikes** [comment]
Gutenberg blocks:
Type validation (similar to JSON data typing)
https://developer.wordpress.org/block-editor/reference-guides/block-api/block-attributes/

**Comment by chachasikes** [comment]
Wordpress RichText handing
* https://developer.wordpress.org/block-editor/reference-guides/richtext/

CraftCMS, Field Types
* https://craftcms.com/docs/3.x/fields.html#field-types

**Comment by chachasikes** [comment]
Maybe this should be the structure:

`Field Label | JS Type | Field Type | Notes`

**Comment by chachasikes** [comment]
Typescript (for reference)
https://www.typescriptlang.org/docs/handbook/2/everyday-types.html (is its own thing - we are more in line with JSDocs / JSON Schema at this point)

Maybe there is a list of common custom field types we can use as an example.

For the Content Model for Per Page Feedback (as another example), there are buttons that return a value Y/N - but in that case, what is the data that's sent to the database - a string with options, or a boolean value that's linked to options.... And is it translatable?

**Comment by chachasikes** [comment]
Note: Contentful has a field "API Type" and "JSON Type"

**Comment by chachasikes** [comment]
Important types to discuss (so far)

* Plaintext
* Richtext
* Datetime
* Media
* Integers (and maybe floats) - for the design system we are mostly taking Content APIs, not data APIs.

Maybe also:
* Boolean: Radio buttons (and their label translatability)

**Comment by xjensen** [comment]
Some old-school inspiration: [RelaxNG Compact Syntax](https://relaxng.org/compact-tutorial-20030326.html). Oh XML, how much I miss you.

Some new-school inspiration: [GraphQL Schema](https://graphql.org/learn/schema/).

**Comment by zakiya** [comment]
What would be an example of a JS Type?

> `Field Label | JS Type | Field Type | Notes`

**Plaintext** - agree 100%
**Richtext** - Gutenberg/WordPress RichText allows the developer to dictate what formatting options are in the field and dictate the block-level parent. I think we need to make Richtext setting recommendations and/or be mindful when creating component that a rich text field input may contain block level elements. My preference would be to have two types of RichText 
      - (1) one that only accepts a defined set of inline tags (i, br, em, strong, a, b, span, etc) and 
      - (2) one that accepts those tags plus a defined set of block level tags (p, div, etc) 
**Datetime** - agree. Should we define a format like  MM/DD/YYYY - hh:mm:ss + timezone ? Maybe this is what you mean by a JS type?
**Media** - agree. .jpg, .gif, .png but not .svg ?
**Integers** - Not sure if we can be looser and say `numbers` instead. If we're dealing with content, a Richtext or Plaintext string can take a number. If we're using the number to program say a width, it might be something like 22.5
**Boolean** - agree. Always handy!


A related thought: I'm trying to decide if this point is moot given our independent component approach but in previous design systems projects we had trouble because components were handed off without clear guidelines about expected variables. So we wouldn't know that for instance a field's _only_ options would be `icon-small`, `icon-large`. We haven't done a ton of work with design tokens yet and some of this might be enforce by our component library tool but I'd like to keep the idea in our heads as we work.
