### ISSUE TITLE
Rocket framework research

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#227]
- Take framework apart to learn how they quickly throw up a site from scratch for a new user without burdening them with config files like .eleventy.js
- Identify optimizations, features we could be using more effectively
- Are there things here that we can learn from in our own 11ty based starter kit project?

Rocket: https://rocket.modern-web.dev/

**Comment by xjensen** [comment]
Interesting framework. 

My initial impression is that it's great _if_ the out-of-the-box layouts, templates, and options serve a project's needs. However, I predict it could become as complicated as 11ty (if not worse) with too much customization.  My assessment here comes from Rocket's emphasis on their **Presets** concept for extending a site. Rocket's Presets could be a neat way to modularize different site functions. But it does require its own learning curve and Javascript overhead/boilerplate.

While browsing the code, I kept thinking, "It would be way easier to do X here, and Y over there, with 11ty version 1.0." Unlike Rocket, we have that luxury because we get to start from scratch. 

So I took that inspiration, and did some experimentation. I think we could create something like a super-11ty-build-system which offers the following. 

* Includes all our default site templates, data, and components.
* Provides 99% of the site's default settings.
* Allows overrides of any data/templates via the project.
* Still requires an `.eleventy.js` file, but it'd be under 10 lines of simple set-up.
* All of the build tooling in the current 11ty-build-system. 

This can be achieved through a combination of 11ty's `setLibrary`, `addLayoutAlias`, `beforeBuild`, and plugin architecture, combined with custom engines for Nunjucks and Markdown. That sounds like a lot, but it's not; I have a working prototype clocking at 30 LOC. I like the idea of providing a tool that's still 100% 11ty, just with all of our boilerplate/settings/templates totally abstracted out of our projects.

**Comment by aaronhans** [comment]
Nice @xjensen that sounds great

30 LOC?

Rocket was helpful getting the component gallery section up quickly but I am already doing a lot of overriding. Rocket also has helpful stuff like image optimization, a service worker. If we put these in our starter kit we can make the defaults fit our needs better.

It would be great to swap this out for our own starter kit so we can improve that while we work on this project.

**Comment by xjensen** [comment]
I was referring to a small prototype I put together when mentioning the 30 LOC bit. It's a practice `.eleventy.js` file that tests 11ty plugins with respect to template/layout overrides. That was the thing about which I was most unsure. But I got it working.

Here it is, for posterity. The final version would be much more robust.

``` js
const Nunjucks = require("nunjucks");
const path = require('path');
const fs = require('fs');

// Create custom Nunjucks environment.
let nunjucksEnvironment = new Nunjucks.Environment(
  new Nunjucks.FileSystemLoader([
    // Templates within the top-most dir in this list take precedence.
    "views/_includes",
    "plugin/_includes"
  ])
);

// Test plugin
const inputPlugin = (eleventyConfig, obj) => {
  // Set the custom Nunjucks environment into 11ty.
  eleventyConfig.setLibrary("njk", nunjucksEnvironment);

  // Using addLayoutAlias (few lines below) allows us to insert/override things in 11ty's layout system.
  let layoutPath = path.resolve(process.cwd(), "views/_includes/layouts/index.njk");
  if (!fs.existsSync(layoutPath)) {
    // Path is relative to the layouts folder, as set in the parent project.
    eleventyConfig.addLayoutAlias('index', '../../../plugin/_includes/layouts/index.njk');
  }
}

module.exports = function (eleventyConfig) {
  eleventyConfig.addPlugin(inputPlugin, {})

  return {
    dir: {
      input: "views",
      output: "dist",
      layouts: "_includes/layouts"
    },
  };
};
```
