### ISSUE TITLE
Create icons for design system component library

### ISSUE THREAD

**Issue by adam-little** [cagov/design-system#246]
Create icons for component library. 

Icons should visually represent the component but be abstract enough that they don’t become out of date as the design of the component evolves.

See FigJam for inspiration: https://www.figma.com/file/iTRca8RQolhmMrOwB62guJ/Component-Illustrations?node-id=2%3A386

Here is list of components based on the [component audit matrix](https://docs.google.com/spreadsheets/d/1bRHQod0tWuULEHIdKaGB2F4M6Lk1py8eGfvu8GyKqng/edit#gid=0):

- Statewide header
- Statewide footer
- Site header
- Site footer
- Page feedback 
- Back to top button
- Link icon
- Page navigation
- Pagination
- Site navigation
- Skip to content
- Accordion
- Card
- Feature card
- Link grid
- Page alert
- Regulatory outline
- Scrollable card gallery
- Step list

**Comment by kkoryaka** [comment]
Added component illustrations to the figma: https://www.figma.com/file/iTRca8RQolhmMrOwB62guJ/Component-Illustrations?node-id=0%3A1

**Comment by adam-little** [comment]
Thanks, Konstantin! 

I like that these are consistent and have enough abstraction that they won't become outdated or be mistaken for the actual design. 

I left a handful of comments on the Figjam board, including: 

- Suggestions for making some of the components more recognizable
- Pointing out places where your list differs from the [Component Audit Matrix](https://docs.google.com/spreadsheets/d/1bRHQod0tWuULEHIdKaGB2F4M6Lk1py8eGfvu8GyKqng/edit#gid=0). My understanding is that the green and yellow components are what we are launching with.

I'll defer to @kmbrlygl for feedback about the overall style.

**Comment by kmbrlygl** [comment]
Ditto to what Adam said, these look great Konstantin! I made some comments as well. 

There are graphic elements (smaller arrows, plus signs, etc.) that are getting hard to see on a small scale. I think we should increase the contrast by playing around with the shades. Maybe even introduce color. I took some time to explore a little and added some samples in the [Figjam here](https://www.figma.com/file/iTRca8RQolhmMrOwB62guJ/Component-Illustrations?node-id=259%3A1290). Let me know what y'all think!

**Comment by Angsv** [comment]
I'm still getting used to figma/slack so apologies.

I really liked the components you designed as well, Konstantin.

I agree with Kimberly about increasing the contrast. The usage of a specific monochrome color can be cool too instead of greyscale.

I was also thinking about making some a bit more graphical and maybe adding a three dimensional look to some of the components (see examples below for Alert and Button Grid )

***@***.***

What you guys think?


-Angelina

**Comment by Angsv** [comment]
Hi everyone,

Kimberly let me know the images didn't show up. I hope this link works for you all (let me know):

Figma Link<https://www.figma.com/file/0X2a9BBV0Vv9YIR57TklMB/Component-option?node-id=0%3A1>

From: Gerasimov, ***@***.***
Sent: Tuesday, January 4, 2022 12:15 PM
To: cagov/design-system ***@***.***>; cagov/design-system ***@***.***>
Cc: Assign ***@***.***>
Subject: RE: [cagov/design-system] Create icons for design system component library (Issue #246)

I'm still getting used to figma/slack so apologies.

I really liked the components you designed as well, Konstantin.

I agree with Kimberly about increasing the contrast. The usage of a specific monochrome color can be cool too instead of greyscale.

I was also thinking about making some a bit more graphical and maybe adding a three dimensional look to some of the components (see examples below for Alert and Button Grid )

***@***.***

What you guys think?


-Angelina

**Comment by kmbrlygl** [comment]
To-do:

- [ ] Move Kontantin's Icon-Illustration into Figma
- [ ] Refine illustrations + blue monochrome color treatment
- [ ] Create into components
- [ ] Add to component library mockup in Figma (with Adam's help)

**Comment by kmbrlygl** [comment]
SVGS of the graphics (illustrations) live in [Google Drive](https://drive.google.com/drive/folders/15f88byNtauuQM4CCFPcsOY4M_9cMX2RR?usp=sharing)
- [Figma component library mockup](https://www.figma.com/file/A1DSo765cWjvBWoLd6tvEE/DS-website-screens?node-id=55%3A7648) reflects how the graphics are scaled and used in a card component

Jon is/will be working on implementing this

**Comment by xjensen** [comment]
I think we can close this per #403.

**Comment by wrendo** [comment]
Need to incorporate
