### ISSUE TITLE
UX Review: Content Navigation component

### ISSUE THREAD

**Issue by chachasikes** [cagov/design-system#25]
# UX Review

A component proposal for the design system needs a UX review.

Initial proposal: https://github.com/cagov/design-system/issues/24
In progress component: https://github.com/cagov/cannabis.ca.gov/issues/53

We have an initial prototype based on our conversations, Slack threads, Figma design files.

Starting this issue to future address what this component needs to be.

Let's collect any insights and information we already know from working on the covid19 project & the design/content design thoughts that went into the Figma design. If there are notes from Google docs & other conversations, let's summarize them here to the best of our ability so that anyone looking at this component can trace its history better.

## Checklist
- [ ] User research
- [ ] Design
- [ ] Content design
- [ ] Content strategy
- [ ] Accessibility
- [ ] Analytics
- [ ] Impact

### User research
*Has user research been conducted?*

### Design
*Anything needed to know about designing this component*

- [ ] Screenshots of Designs
- [ ] Notes on responsive design?

#### Screenshots
*You can include a public link to a design asset, but please provide design screenshots at 100% size so that everyone can see the design.* 

### Content design 
*What content elements or assets does a content editor need to provide?*

### Content strategy
*What does a content editor need to know about writing and publishing this type of content?*

### Analytics
*How can we measure if this component is succeeding in its intention, or discover new insights about needs that we did not know?*

### Impact
*Are there potential impacts of this component or how it is used that may need special consideration? (Impacts could be in equity, accessibility, privacy or other concerns, or opportunities)*

**Comment by chachasikes** [comment]
Based on development work & conversations, these are some of the interaction notes we had about this component. Let's record these as design requirements.
* Sticky position
* scroll margin (CSS selector not working in WP, may have a conflict we need to track down)
* Mobile stying / behavior example

Future design/interaction/navigation improvements to consider
* highlight section on navigate
* include anchor in URL hash.

**Comment by chachasikes** [comment]
In the Technical review issue I made a note that maybe we want to spec out the "insights" part of the component definition in this issue AND do a technical review about how we implement it.

@adam-little Can you check with Insights team to see if they want to track or measure clicks? It might be out of scope on day 1, but would be good to know if this is something we would want to do & if we do want it...  how? cc @wrendo

**Comment by chachasikes** [comment]
(See that mobile layout needs adjustment for the page template)

**Comment by adam-little** [comment]
@chachasikes Here is an update to the "Design" section:

### Design

#### Summary of functionality
This component serves as a table of contents for the page. Each link has a matching H2 in the page content. Selecting a link will take the user to the corresponding section on the page. Since the component is fixed to the top of the page when scrolling, a user can easily skip between sections.

#### Notes about design

- This component is 25% the width of the page and moves the main content column to the right.
- When scrolling down the page, this component will become fixed/sticky at the top of the screen.
- When scrolling down the page, the links become active to indicate what section a user is currently looking at [POST MVP]

#### Notes on responsive design

- On smaller screens, this component will appear under the h1 page title.
- To reduce page height, the component title (On this page) will become hidden.
- When scrolling, the component will collapse into a drop down menu and will become fixed to the bottom of the sticky header. It will assume the same scroll behaviors of the page header.

#### Screenshots
On desktop:
![Frame 12](https://user-images.githubusercontent.com/69167298/122294475-14a2eb80-cec6-11eb-98e9-b560942aa211.png)

On mobile (appears under page title):
![Frame 34](https://user-images.githubusercontent.com/69167298/122294539-27b5bb80-cec6-11eb-8691-b9197cd60831.png)

Collapsed state on mobile (fixed to sticky header):
![Frame 35](https://user-images.githubusercontent.com/69167298/122294618-3d2ae580-cec6-11eb-9b3e-0a29a49b8e7d.png)

Collapsed state expanded:
![Frame 24](https://user-images.githubusercontent.com/69167298/122294660-49af3e00-cec6-11eb-9384-63f14a6ca193.png)

#### Design file
https://www.figma.com/file/9FTGOPO5HlsLfYuNrtL9IM/cannabis.ca.gov-screens?node-id=439%3A3287

#### Inspiration
[https://www.drinkaware.co.uk/facts/health-effects-of-alcohol/effects-on-the-body/alcohol-and-sleep#drinkingcanequaladisturbednightssleep](https://www.drinkaware.co.uk/facts/health-effects-of-alcohol/effects-on-the-body/alcohol-and-sleep#drinkingcanequaladisturbednightssleep)

**Comment by adam-little** [comment]
@m-sullivan7 assigning to you to provide documentation for content

**Comment by m-sullivan7** [comment]
@wrendo Any update on if we've figured out what the work required here is?

**Comment by chachasikes** [comment]
We shipped this. These are the historical issues for design system components, keeping the ideas and intentions behind components we are building for the design system in one place. 

Closing.

**Comment by chachasikes** [comment]
Other work on this can be in other tickets tagged with the component label `Component - content-navigation` to help us find all related issues and review historical issues. This can be helpful for future team members.
