### ISSUE TITLE
Back to top component needs work. 

### ISSUE THREAD

**Issue by zakiya** [cagov/design-system#264]
Changing the `data-hide-after` attribute doesn't do anything on the back-top-top component. I verified this with manual testing and by debugging the source code (`timer` is always null)

@aaronhans Assigning to you for two reasons:

- A demo of this component will be tricky because it's designed to work in interaction with the entire page. In my local testing I fill the page with lorem ipsum.
- We should remove the data-hide-after attribute from the **Sample markup**.

cc @chachasikes

**Comment by aaronhans** [comment]
I am doing some testing with this component in the design system now.

- I added the component code to the main bundle so it appears everywhere on the site now since the custom element was already in the footer
- The data-hide-after attribute is working as expected for me, I am able to provide larger and smaller value and see the component leaving view faster and slower

One point that was confusing to me was that the behavior is designed so that it only initially appears when the user begins to scroll back up.

I think we should explain that in the readme.

What if we changed the end of the top section from:

The button disappears after 7 seconds. If someone scrolls again, it will reappear.

to:

The button appears when the user has scrolled past the first screen and begins to scroll back up. It disappears after 7 seconds. If someone scrolls again, it will reappear.

What do you think @zakiya and @m-sullivan7?

**Comment by m-sullivan7** [comment]
I support that language if @zakiya is good with it. 🙂

**Comment by zakiya** [comment]
@aaronhans can you record screen or maybe we can pair? I'm still not seeing it disappear after 7 seconds.

**Comment by zakiya** [comment]
Local video:

https://user-images.githubusercontent.com/915352/150197406-0cf6d110-5994-4cee-85cb-aca6a51d201c.mp4


and the code that I'm testing : https://github.com/zakiya/odi-ds-content-tests/tree/main/ds-back-to-top

**Comment by aaronhans** [comment]
I opened a PR to your personal repo with changes that make the demo work as expected https://github.com/zakiya/odi-ds-content-tests/pull/1

**Comment by zakiya** [comment]
@aaronhans Thanks for those changes! It makes sense that the doctype is needed. I was still a bit confused about the behavior.  In addition to your suggestion I would add:

"The button appears when the user has scrolled past the first screen and begins to scroll back up. It disappears after 7 seconds **by default**. If someone scrolls again, it will reappear. **If the user reaches the top of the page at any point, the button will disappear right away.**"  

Do you want to work on the [demo in the design system](https://designsystem.webstandards.ca.gov/components/back-to-top/readme/#demo-and-sample-markup) website or should I?

**Comment by aaronhans** [comment]
I like the description updates you have there @zakiya

The back to top is in the main bundle so shows up on all pages on the design system site now.

What if we changed the sample markup/demo setup in this page to be just plain HTML with no preview but added language saying the component can be seen at the bottom right on this page if you scroll down then back up?

**Comment by zakiya** [comment]
I like that idea @aaronhans !

**Comment by aaronhans** [comment]
Cool PR here https://github.com/cagov/design-system/pull/399

@m-sullivan7 you are tagged on it, let us know if you approve of the latest content changes

**Comment by m-sullivan7** [comment]
PR approved. Thanks!
