### ISSUE TITLE
Component: pagination

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#28]
The cannabis site uses pagination to move between the press releases and other content types. We will create a reusable web component that can call external APIs to determine:

- How many pages to display

The component will display links to all available page sets, prev and next active when available

The component will emit events on click to notify other components on the page about new click events

---

### Checklist
- [ ] Name
- [ ] About this component
- [ ] Description
- [ ] Examples (ca.gov)
- [ ] Examples (design systems)
- [ ] Features
- [ ] Requesting agency

### Name
*What should we call this component in conversation?*

# About this component
*Please tell us more about the component.*

### Description
*Describe how this component will be used.*

### Examples from ca.gov properties
*(Can be screenshots, a few examples is great. Please include URLs if the examples are live.) This helps everyone understand what you are referring to.*

### Examples from other design systems
*If this component is commonly found in other design systems, please link to it. This helps everyone understand real-world examples of this idea.*

### Features
*Critical features to support initially.*

### Requesting agency
*Who is requesting this component?*

---

Thank you!

[Learn more about our review process.](#tbd)

**Comment by aaronhans** [comment]
Component checked in: https://github.com/cagov/design-system/tree/component-feedback/components/pagination

Viewable on github pages: https://cagov.github.io/design-system/components/pagination/preview-basic.html

**Comment by adam-little** [comment]
@aaronhans Here is some feedback. You can also view detailed designs in the[ "Components and Styles" board on Figma](https://www.figma.com/file/9FTGOPO5HlsLfYuNrtL9IM/cannabis.ca.gov-screens?node-id=439%3A3287).

- Please remove border and hover state from ellipsis since these are not buttons or links.
- Please remove left and right padding from ellipsis so that they do not consume as much space as the buttons
- Please confirm 8px of spacing between each button
