### ISSUE TITLE
Make improvements to design system color palette 

### ISSUE THREAD

**Issue by adam-little** [cagov/design-system#304]
Currently, our system of shades and tints is resulting in a lackluster color palette with limited options for designers.

Let's explore how we can create a more robust and intentional color system, without dramatically changing the overall look and feel.

**Comment by adam-little** [comment]
Inspiration: https://learnui.design/blog/color-in-ui-design-a-practical-framework.html

**Comment by xjensen** [comment]
That's a great article, and I think it's the right direction. Understanding and manipulating hue, saturation, and brightness results in much richer, more vibrant color palettes. It's difficult to get it **just right** in my experience, but I think it's worth the effort. 

[This article about building color palettes](https://www.refactoringui.com/previews/building-your-color-palette) might prove useful as a means to start experimenting. In particular, I like the sections toward the middle about how to iteratively choose each color by "filling in the gaps".

**Comment by kmbrlygl** [comment]
Courtney shared this PDF of a color palette she worked on that shows accessibility:
[CCCCO-brand-refresh-colors.pdf](https://github.com/cagov/design-system/files/8113109/CCCCO-brand-refresh-colors.pdf)

Also, Deque has an accessible color contrast checker that outputs color suggestions and takes into account font size and weight:  https://color-contrast-checker.deque.com/

**Comment by kmbrlygl** [comment]
> On the topic of accessibility, here's [another interesting tool to consider](https://accessiblepalette.com/).

Ahh, this is awesome, Jon! I went on a bit of a spiral learning about that CIELAB color model. I've been working with HSB and having trouble figuring out a system since I still have to do optical adjustments. Looks like CIELAB is already considering luminance, as well as accessibility. I'm definitely going to reference this!

**Comment by xjensen** [comment]
Getting a light-balanced color palette like the one advocated in that tool would be a dream. It takes so much of the guess work out of finding accessible color pairings.

**Comment by kmbrlygl** [comment]
UPDATES

## Work done:
- Shared with design team (ODI and CDT) CIELAb model approach to color and accessibility ([Figma](https://www.figma.com/file/3N4dFWhFqiGpWr1DRQoJUM/Design-system-colors?node-id=567%3A1036)/[Loom Video](https://www.loom.com/share/1ba51cb75b654d458ffafe9e64e739ff))
  - I did an [HSB exploration](https://www.figma.com/file/3N4dFWhFqiGpWr1DRQoJUM/Design-system-colors?node-id=476%3A1089) but it was difficult to systematize since it requires optical adjustments

- Tested CIELAB generator out with [Cannabis colors ](https://www.figma.com/file/3N4dFWhFqiGpWr1DRQoJUM/Design-system-colors?node-id=608%3A1754)(a project with existing branding) as suggested by team and learned: 
  - Palette keeps the tone of the starting colors (.e.g, bright colors create vibrant palettes, muted colors create subtle or elegant palettes)
  - You _can_ substitute brand colors into the level it looks closest to...however, the CIELAB color outputs are a close match. My recommendation is to use the CIELAB generator's color outputs because it assumes there's a designer on the team confident to make those swaps to the color palette. 

## Currently doing:
 - Working on documentation of how we would use CIELAB in the system. Here's the [draft to start](https://docs.google.com/document/d/1xRHMQ_BFYTBI48Jgs9IuKoyrZOfMe-Hho_HhmpXvGB8/edit?usp=sharing). I'm gathering feedback/ideas from Konstantin, Angelina, and Adam.

**Comment by kmbrlygl** [comment]
I think this is ready to move forward with (anticipating we will iterate on this more in the future).

I am finishing up the documentation and will need to run it by @m-sullivan7. I'll try to get this portion in by this sprint as well. 

@kkoryaka here's are the tables for updated and new colors + tokens. 

## Grayscale
Name | Updated color (hex)
-- | --
gray-50 (new token) | #FAFAFA
gray-100 | #EDEDEF
gray-200 | #D4D4D7
gray-300 | #BCBBC1
gray-400 | #A4A3AB
gray-500 | #898891
gray-600 | #72717C
gray-700 | #5E5E6A
gray-800 | #4A4958
gray-900 | #3B3A48

## System Status Tokens

New token | Replaces existing token | Updated/new color (hex)
-- | -- | --
success-100 |   | #E5F1E7
success-300 |   | #9AC7A4
success-500 |   | #489B62
success-700 | success | #0F6D38
success-900 |   | #154425
danger-100 |   | #FCE9E8
danger-300 |   | #EEABA9
danger-500 | danger | #D5676A
danger-700 |   | #B91B37
danger-900 |   | #721923
warning-100 |   | #FFEF97
warning-300 | warning | #DCBA00
warning-500 |   | #A38900
warning-700 |   | #6F5E00
warning-900 |   | #463B00
info-100 |   | #EDEDF6
info-300 |   | #B9B9DC
info-500 |   | #8585C2
info-700 |   | #5555AA
info-900 | info | #2B2B95

## Product/Brand palette

New token | Previous/current token | HEX
-- | -- | --
primary-100 | primary-lightest | #E7EEF9
primary-300 | primary-light | #A3BEE7
primary-500 |   | #5A8AD4
primary-700 | primary-color | #165AC2
primary-900 | primary-dark | #003688
accent1-100 | secondary-lightest | #FFEAD6
accent1-300 | secondary-light | #FFA656
accent1-500 | secondary-color | #DE6516
accent1-700 |   | #9C4510
accent1-900 | secondary-dark | #642A0A
accent2-100 | highlight-lightest | #FFECC4
accent2-300 | highlight-light | #ECB32D
accent2-500 | highlight-color | #AC8227
accent2-700 |   | #775A20
accent2-900 | highlight-dark | #4A3918

Please let me know if you have any questions!

**Comment by kmbrlygl** [comment]
@m-sullivan7 content is ready for review: [Color - CEILAB System Documentation](https://docs.google.com/document/d/1xRHMQ_BFYTBI48Jgs9IuKoyrZOfMe-Hho_HhmpXvGB8/edit?usp=sharing)
Pages 1-4 are for your editing/review. You can ignore the other parts (they are mostly notes). Please let me know if you have any questions. Thanks in advance!

**Comment by m-sullivan7** [comment]
Thanks! It's on my list. 🙂

**Comment by m-sullivan7** [comment]
@kmbrlygl I made a first pass with edits from a content design perspective. Some were about highlighting what seemed to be the key messages, others were about reducing sentences that were hard to read.

I had some questions around specific terms that were unfamiliar to me and made comments in those areas. I ask about them because they could be opportunities to use a plain language term. That said, this content is at reading level 6 as is, which is great!

I would be happy to meet to talk about my suggestions or explore some of the comment areas. 🙂

**Comment by kmbrlygl** [comment]
Update 4/11:
- I shifted our system palettes and updated the color palette library in Figma. 
  - I am working on updating the color table to better fix accessibility issues. I will confirm with Konstantin when these are ready (very soon)
- Will need to meet with the design team to figure out how we might address using colors that aren't design tokens or how to go about creating new tokens. This is related to button colors and interactivity.

**Comment by yesenia-gtz** [comment]
@kkoryaka @timothyshambra is this ready to merge to this week's release?
