### ISSUE TITLE
Bug: Sass converting transparent attributes values to 0 0 

### ISSUE THREAD

**Issue by chachasikes** [cagov/design-system#397]
Jon spotted an issue with the feature card variations background color - where Sass is converting 
`background: transparent` to `background: 0 0`

We are not sure why. Let's find out.

**Comment by zakiya** [comment]
All instances of `background: transparent;` should be changed to `background-color: transparent;`.  *background* is a shorthand property and should really only be used when declaring several properties at once because you can unintentionally override other properties if you’re not careful. - especially when using background images.  The sass converter respects the word `transparent` on *background-**color*** but not *background* that could be a bug but I also think we should use best practice here.
