### ISSUE TITLE
Principles page: accessibility example

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/design-system#413]
On the [main principles page](https://designsystem.webstandards.ca.gov/principles/), in the example for principle 8, _Optimize performance_, we provide this example:

> Websites built with the design system have a Lighthouse performance score X% higher than the average CA.gov website.

What number should we use for `X%`?

Tagging @aaronhans to start the discussion.

**Comment by mediajunkie** [comment]
I recall a comment in the presentation last week that suggested Lighthouse scores may vary depending on the local environment, so let's try to make our number bulletproof or at least able to withstand pushback from people who may feel judged.

**Comment by aaronhans** [comment]
The comment during DWSN was that the presence of browser plugins could influence the lighthouse score. This is true if you are running lighthouse in your local browser which is pretty convenient because it is integrated into chrome's dev tools panel.

We kickoff lighthouse runs from several different perspectives:

- When we run our leaderboard analysis we run the lighthouse application from the command line. This is not subject to browser resource differences
- We use web.dev/measure which sets specific throttles on lighthouse and makes sure those resource allocations are present and not exceeded
- We use https://calibreapp.com/ to run daily performance audits against our systems to catch regressions. This runs lighthouse on their servers which have consistent resources available and applies the required cpu and bandwidth throttles.

The commenter during DWSN recommended webpagetest which is an excellent resource. We often make use of that to create side by side performance comparison videos to show the lag caused by heavy javascript. This is an excellent resource we should use more.

**Comment by aaronhans** [comment]
I recommend we say something different regarding performance. We cannot guarantee that websites using design system components are performant because other resource hungry items may also be present. We see this with cannabis both the WordPress monolith and the headless version use design system components but the headless version is faster even though they both look the same to the end user.

<img width="826" alt="Screen Shot 2022-01-24 at 10 05 19 AM" src="https://user-images.githubusercontent.com/353360/150839179-a2d86dff-6792-4197-8d7a-9e95668823ae.png">

We could say that design system components do not add much weight. We could measure the total code size of all design system components (This is a common approach). We could mention that all sites ODI has shipped with the design system exceed 90 lighthouse score when throttled to low mobile cpu/Fast 3G bandwidth  settings

**Comment by m-sullivan7** [comment]
I'd be happy to say something different.

- If we go with total code size, we'll need to remember to update this number when we issue new versions of components or add components.
- If we go with a statement on all sides ODI has shipped with the Design System, we'll need to check this every time we publish a site.

The second sounds like it's easier to maintain, but I'm agnostic on which one we choose. 🙂

**Comment by m-sullivan7** [comment]
@aaronhans reviving this conversation since this is a P1 issue. Which of the measurements you proposed would you like to go with? The "all sites ODI has shipped with the design system exceed 90 lighthouse score when throttled to low mobile cpu/Fast 3G bandwidth settings" version seems like it requires less maintenance over time.

**Comment by aaronhans** [comment]
Yes I agree, that is a standard we hold ourselves to and won't have to update constantly

**Comment by mediajunkie** [comment]
let’s print it!
-- 
Christian Crumlish
Product Manager | Office of Digital Innovation
Digital Crisis Standard
<https://github.com/cagov/covid19/wiki/Crisis-Standard> - covid19.ca.gov
415-672-5759 | ***@***.***

Follow us:
web <https://alpha.ca.gov/> | blog <https://medium.com/cadotgov> | twitter
<https://twitter.com/cadotgov>

**Comment by m-sullivan7** [comment]
Excellent. I'll make an edit with this (let me know if I need to tweak--luckily it's easy to do!):

> Websites built by the Office of Digital Innovation with Design System components have Lighthouse scores of 90 or more when throttled to low mobile CPU or Fast 3G bandwidth settings.

**Comment by m-sullivan7** [comment]
[Principles page](https://designsystem.webstandards.ca.gov/principles/) updated with new example. Closing this ticket as done. Thank you all!
