### ISSUE TITLE
Header on skip to content page is wedged

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#432]
Seen on Chrome desktop on mac

Looks like it is caused by the id value on the header. Not sure why that id is on that element

**Comment by aaronhans** [comment]
<img width="680" alt="Screen Shot 2022-01-24 at 1 09 01 PM" src="https://user-images.githubusercontent.com/353360/150865234-f10b9f2d-b444-42ab-851d-6d320fadbbba.png">

**Comment by xjensen** [comment]
This is happening in the markdown renderer. It's automatically adding an `id` to every heading. This happens to conflict with the actual back-to-top anchor on this page.

One solution would involve passing options into [our instance](https://github.com/cagov/design-system/blob/d7937d5c1f99fb65d7c5c50026a59aca0660895a/docs/src/11ty/markdown.js#L9) of [markdown-it-anchor](https://github.com/valeriangalliat/markdown-it-anchor). We could revise the `level` option so that it doesn't process `<h1>`.
