### ISSUE TITLE
iPhone: Setting larger font in accessibility settings doesn't change site font

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#454]

**Comment by chachasikes** [comment]
I will look at this and try to diagnose what's wrong - then pass to @kkoryaka

**Comment by chachasikes** [comment]
This is a good check to also do in our accessibility + design QA cc @adam-little @kkoryaka @zakiya @aaronhans @xjensen 

This is true - setting the larger text size in iPhone accessibility has no bearing on the site.
But there are additional instructions to make this work, and I was able to resize this on iPhone XR.
https://mcmw.abilitynet.org.uk/making-text-larger-safari-ios-13-iphone-ipad-and-ipod-touch

In the URL bar there is a text button that can be touched to change the size. While I have seen the button thousands of times, I didn't notice it & wish I had known because I can't read tiny text on my phone - sometimes even with glasses because to get the glasses to focus, the phone needs to be like 18" away - and if the text is tiny then it's too far away to see it. Yay for this button. Boo for Apple not making sure I know - a tip on the Accessibility settings page would be helpful. cc @britt-allen 

@thepegisin probably knows all about this 👁️

**Comment by chachasikes** [comment]
Adding to next sprint - would be nice to review this issue and think about our QA practices for testing typography on mobile devices.

**Comment by jaredwyee** [comment]
Per planning discussion, the impetus issue is due to iOS/Safari usability issue. Chach confirmed that the font size does update if you find the right function/setting in iOS Safari. Marking won't do.

**Comment by zakiya** [comment]
Just adding a supporting note. 

The settings on an IPhone at Settings  > Accessibility > Display & Text Size affect Safari's app text like the in the address bar and Favorites list. Actual website text is adjusted the way Chach listed above. 


Related Apple support links:

https://support.apple.com/guide/iphone/display-text-size-iph3e2e1fb0/ios#:~:text=Go%20to%20Settings%20%3E%20Accessibility%20%3E%20Display,using%20the%20Font%20Size%20slider.

https://support.apple.com/guide/iphone/customize-your-safari-settings-iphb3100d149/ios
