### ISSUE TITLE
iPhone: Mobile header menu placement doesn't match Figma

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#469]

**Comment by adam-little** [comment]
Header with site logo:
![image](https://user-images.githubusercontent.com/69167298/151225883-5b327b9e-a0db-4e06-9981-041ca329c318.png)

Header without site logo:
![image](https://user-images.githubusercontent.com/69167298/151225921-271a2cdf-41b9-4bfe-bb34-1e01fbc97f3c.png)

Menu expanded:
![image](https://user-images.githubusercontent.com/69167298/151225958-956d983d-9a98-462d-bf5b-84db6f7db9b3.png)

Submenu expanded:
![image](https://user-images.githubusercontent.com/69167298/151225988-ba2b4d7d-fcd5-46bf-9745-909f21c30834.png)

See Figma: https://www.figma.com/file/veQuKQHf8gK5JdFEoMLGRD/UI-Design-kit?node-id=3%3A2392

**Comment by zakiya** [comment]
@adam-little Just to confirm, do you want us to move the hamburger above "State of California Design System"? 

It looks like this is already done for cannabis (which has a logo instead of a name) but not for drought and the design system. 

Design system:
![CleanShot 2022-02-01 at 15 38 22](https://user-images.githubusercontent.com/915352/152069643-d55816fe-5a04-4132-8baa-4ba657a3ee4c.png)

Cannabis:
![CleanShot 2022-02-01 at 15 38 43](https://user-images.githubusercontent.com/915352/152069673-343b7d79-ee4d-491c-9a5d-be2b061413d6.png)

Drought: 
![CleanShot 2022-02-01 at 15 39 06](https://user-images.githubusercontent.com/915352/152069705-e9f09da5-c9e2-4fdc-8e52-f2f06569a1ce.png)


Figma: Header without site logo:
![151225921-271a2cdf-41b9-4bfe-bb34-1e01fbc97f3c](https://user-images.githubusercontent.com/915352/152069394-0a018dbb-2373-4da6-8999-f17b834d3dd3.png)

**Comment by adam-little** [comment]
Here are the alternatives....

1. Right-aligned
![image](https://user-images.githubusercontent.com/69167298/152206610-975b8f0a-b297-44dc-8e7b-0c17b7e68847.png)
IMO, this doesn't feel balanced when search/menu are right aligned and the website title is left aligned

2. Vertically aligned with "State of California"
![image](https://user-images.githubusercontent.com/69167298/152206797-7dac9871-d2f1-4740-8fa7-b6305e6932f1.png)
I think this looks OK on larger mobile screens, but risks becoming cramped on smaller screens or when text is translated to languages that have more characters.
