### ISSUE TITLE
General: Need shorter code blocks in component pages

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#476]
They're just too long and it's bad UX for reading content

**Comment by xjensen** [comment]
Working on this piecemeal via #677, but should probably keep this issue open.

**Comment by chachasikes** [comment]
@xjensen would it help if we scheduled this issue in a sprint rather than leaving it in in-progress & a perpetual state of obligation?

**Comment by xjensen** [comment]
@chachasikes I think we're near the point where continuing this work will require significant, breaking changes to the components themselves. 

I'm all for it. I've been beating that drum since October. But perhaps it makes more sense to create new issues for each component. If so, we could close this.

**Comment by yesenia-gtz** [comment]
Need to workshop as a group to identify best solutions. useful example.
