### ISSUE TITLE
Need 404 page

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#479]

**Comment by adam-little** [comment]
This is the design that we have [in Figma](https://www.figma.com/file/veQuKQHf8gK5JdFEoMLGRD/UI-Design-kit?node-id=5%3A3009).

![image](https://user-images.githubusercontent.com/69167298/151218512-993823bb-23c0-4d4d-9986-3265e815aecb.png)

For the DS website, we can remove the search bar.

**Comment by wrendo** [comment]
I think that works.

**Comment by xjensen** [comment]
I have an [example](https://479-add-404-page.pr.designsystem.webstandards.ca.gov/error.html) ready in PR #572. 

One important difference is that we don't have a search box on the Design System site yet. Open to suggestions if there's anything else we can do at this time. I tried linking to a site-specific Google search, but Google hasn't indexed our site yet.

It's also important to note that this page will not appear for 404s in our PR preview site. The PR preview sites are a little special and don't support this yet. But it should work in production.

**Comment by wrendo** [comment]
Looks good to me.

**Comment by xjensen** [comment]
Cool, I merged it into the site to stop the bleeding, for now. We can change it any time.

**Comment by xjensen** [comment]
Another thing to consider:

<img width="1258" alt="Screen Shot 2022-01-27 at 12 49 14" src="https://user-images.githubusercontent.com/1208960/151441405-2fb5255e-a3f8-4204-a76c-1f4e9eaba9a5.png">

Asking "Did you find what you're looking for?" right underneath "We can't find what you're looking for." is a little silly. But I could see the argument for keeping some form of feedback here, since we may be able to solicit very useful information in this situation. 

I may put in an additional PR to suppress page feedback on the error page, for now.

**Comment by adam-little** [comment]
I had the same thought @xjensen. If i'm not mistaken, most people arrive at a 404 because:
- Typo (in which case the form is not helpful)
- Broken link (in which the case form may be helpful)

**Comment by xjensen** [comment]
@adam-little That sounds right. If I had to guess, broken links would be the more common case. On Drought, for example, most of the 404s were due to outdated links on Google.
