### ISSUE TITLE
Page alert example refresh after closing?

### ISSUE THREAD

**Issue by wrendo** [cagov/design-system#502]

**Comment by chachasikes** [comment]
Not sure what this means:

Jon thinks this may be interpreted as a button to reset the code demo after messing with it.

**Comment by jaredwyee** [comment]
@aaronhans @xjensen I dont know what this issue is for. Any guidance on how to confirm it is working/fixed?

**Comment by aaronhans** [comment]
The page alert component page viewable in the release preview here https://1-0-1-rc-post-launch-fixes.pr.designsystem.webstandards.ca.gov/pr/1-0-1-rc-post-launch-fixes/components/page-alert/readme/

Has  new "reset demo" link above the interactive demo embedded in the readme documentation. This is supposed to let the user return the demo to its initial state which is helpful with this component because clicking the x dismisses it.

**Comment by jaredwyee** [comment]
Oh I get it. Confirmed clicking reset demo reload the page alert. Minor thing is there's no hover state for "Reset Demo" so you don't know it does anything until you click it. Tolerable behavior though.

![image](https://user-images.githubusercontent.com/85529382/153284674-41c4affb-4f57-45cb-a0e7-967f05052ea3.png)
![image](https://user-images.githubusercontent.com/85529382/153284697-fc38018f-a476-419c-bf5f-634ec7a270a8.png)

**Comment by aaronhans** [comment]
I'll let @jaredwyee make the call on urgency.

Once we have a fix I'd like to make sure @kkoryaka gets to review it because he was changing some button styles recently

**Comment by jaredwyee** [comment]
Sorry I inadvertently moved this DONE not realizing there was more comments. @xjensen @aaronhans. Will move this back into in progress.

If a hot fix is safe to do, go a head but this isn't urgent by any means so if we'd rather adhere to the new release schedule, let's do that.

**Comment by xjensen** [comment]
I've put a fix into the current sprint at #666. Not going to do a hotfix here.
