### ISSUE TITLE
Create styling for "alpha" "beta" tags on component library cards

### ISSUE THREAD

**Issue by adam-little** [cagov/design-system#561]
Design the tags on the component cards so that it can be easy to know what maturity stage they are in (current says "**Alpha**" in bold)
![Screen Shot 2022-04-25 at 2 07 21 PM](https://user-images.githubusercontent.com/20393247/165175226-61ac9fa1-9261-467b-9fae-815da82bb13d.png)

**Comment by kmbrlygl** [comment]
This is where the design landed as of 3/14 - [Figma](https://www.figma.com/file/A1DSo765cWjvBWoLd6tvEE/DS-website-screens?node-id=1280%3A14064)

**Comment by kmbrlygl** [comment]
Updates since this design was contingent on color tickets:
- used the updated color palette + the teal-green color (not yet established tokens)
  - we did this because accent colors 1 (yellow) and 2 (orange) were too similar to be clearly distinguishable

[Figma link](https://www.figma.com/file/A1DSo765cWjvBWoLd6tvEE/DS-website-screens?node-id=1280%3A14064) is up to date:
![Screen Shot 2022-04-25 at 2 10 23 PM](https://user-images.githubusercontent.com/20393247/165175622-9f04775c-68a5-4519-8eb9-0f1482bb3e36.png)

Optional functionality: filters for component maturity stage (will need to scope this out)
