### ISSUE TITLE
translations for component sample markup integrated into demos

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#589]
Break this into component efforts:

- [ ] ready components for translation
- [ ] translate component content
- [ ] translate site content

**Comment by chachasikes** [comment]
I will help with defining what we need to do here

**Comment by chachasikes** [comment]
Idea: "translation captain" works with "sample markup" captain

**Comment by chachasikes** [comment]
There are a few patterns of translations we have worked with.
* Google Translate widget
* Translation pipeline (use compiled data from translated API to render language-specific content)

We were discussing methods for having custom content by language as well.

## Suggestions
1. "Ready components for translations"

We have already worked to make the components translatable. Recommend that:
* We add a section on the design system site for communicating about translation specifications, and provide supplemental guidance on getting translatable content to play well in designs and front end pages.
* We develop "translation captains" or "reviewers" for the design system components to give feedback on translation system integrations.
* Continue to keep the content models updated for each component, because this shows where and how content is integrated into a component.

### Approach
Keep content strings in a place where they can be edited by content editors or translators.
Generally, we are doing this by specifying that translatable strings live in markup only - either in inner HTML, data attributes, JSON files or other API data organized by language code.
* This means that translatable content should not be hard coded in CSS or JavaScript. 
* Moving settings files that render content can also include a language structure by language code.

Component reviewers need to look for strings that are hard-coded.

### Language layout
In addition to keeping the content strings adjustable, the markup and class structures of the pages also needs to work right to left (RTL). 
* Recommend we create a guide on doing this well.

**Comment by chachasikes** [comment]
2. Translate component content

There are a few pieces of component content that need to be translated.
A. The sample markup examples. 
This is higher priority because we need to be able to test the components behavior in different languages. 
To do this, we need:
- [ ] - Realistic demo content in multiple languages so that the user feedback can catch any problems with layout and content structure that might not be obvious when using filler text like lorem ipsum. 
- [ ] - Consider this principle: Our first priority is content design, make sure our components support good content design in all languages.)


B. The README's and other documentation 
Recommend that we connect this effort with general website translation efforts.

**Comment by chachasikes** [comment]
3. Translate site content

There is an initiative on improving translatability of State website content.
(- Q: does the initiative have a website?)

FWIW: ODI team members have expressed these preferred patterns for translating content: 
1. Multilingual content designers on product teams
2. Translation services with system for integrating translated content into the site.
3. Auto-translations (exploring machine learning options)

Every content platform requires a translation pipeline. 
The pipelines are very dependent on the technology used to manage published content. We could provide some recommendations on how to streamline this, based on lessons learned from covid19.ca.gov.

@jaredwyee is the point person on this.

**Comment by chachasikes** [comment]
Next steps:
Go over these ideas and decide which steps we want to take now, and which connect with other initiatives.

**Comment by chachasikes** [comment]
Propose we make this the focus of a future sprint. Maybe 1.0.3 or 1.0.4.

We have some planning conversations to do that could go into 1.0.2
cc @aaronhans @jaredwyee

**Comment by chachasikes** [comment]
And for actionable item - planning in next sprint:
* What a translatable component looks like (code issues to check for on review - develop a list that we can include in our docs)
* Review status of our components and note components that have issues.
* Consider including a checklist for major version updates (in the changelog?) - where we can check that we did review it for translations (or accessibilty, etc) - would also be helpful to put this in Airtable as database because reading each changelog and memorizing it, or digging up github issues is not a sustainable way for anyone to keep up with this & we may need more visibility as our numbers of components grow.

Later sprint:
* Include a Translate button in code demo that can display examples in other languages and RTL
* Work out data structure (Note: have done some of this work for covid19 - (is in Storybook instance for multilanguage PDF dropdown - might not be in main branch - need to dig it up)
* Develop a guidance page on how we support and test RTL in markup - there are many technical rules here, and it would be helpful to clarify which rules or rendering methods are at play in a given component. (Thought: this could be a good community project - maybe with language taskforce?)

**Comment by chachasikes** [comment]
Chach, Jared, Yesenia met Feb 16 to discuss translation epics and the different ways translatability applies to the Design system.
Project notes: https://coda.io/d/CA-gov-Product-Team_dKL2z4BbUHn/DS-Meeting-Notes_su1LX#_luwSK

Actions for Feb 22-26
- [ ] Chach - draft initial translation checklist & "Translatability" section for design system docs (reviewing 1-3 components)
- [x] Jared - share list "Languages other than English (with at least 1,500 LEP adults)" (Shared in Slack)
- [ ] Jared - review sample markup to look for components that could include translatable content

Actions for future sprint
- [ ] Add language list to coda.io 
- [ ] Feedback on translation technical review checklist (ODI + CDT)
- [ ] Divvy up components and have all engineers do review of 1-3 components for translatability
- [ ] Quick retrospective to update the translation checklist
- [ ] Deeper discussion on design, layout and RTL spec/support.

**Comment by chachasikes** [comment]
Added a doc into Coda on Translations.
Next steps are scheduling work. Recommend we do in a dedicated sprint (maybe 1.0.5 or 1.0.6)

**Comment by yesenia-gtz** [comment]
@yesenia-gtz to review and assign separate issues
