### ISSUE TITLE
Issue: Design System Issue Proposal Template Feedback

### ISSUE THREAD

**Issue by zakiya** [cagov/design-system#609]
I decided to ~~try eating our own dogfood~~ user test by using our issue template for Icons https://github.com/cagov/design-system/issues/608

### Questions:
1) Is anyone notified when a new issue is created if it doesn't wind up on the board?
2) Do we have a link yet for "Learn more about our review process."?

### Notes:
- I started typing in between checkboxes in the list before realizing they were referencing headers below. Recommend moving the checkbox to the bottom. 
- **Requesting agency** seems limited. It's just  a few folks on our team at this point, it wouldn't be inaccurate to say "ODI"
- I didn't know how **About this component** and **Description** were different
- **Background** and **Requesting agency** should be switched in the checklist order
- I think we should suggest specific other design systems to check out. In my case, it was useful to see how other design system deal with icons.
- I had some features to add that weren't critical

Here's a gist with how I would remedy my own notes:

https://gist.github.com/zakiya/0029c3fd480b4907a3d7b437b3ae125b

**Comment by chachasikes** [comment]
Thank you so much for using the template.

1. We can assign a Github team and add people to the team. Right now, no, because we have not decided who will get the notice. For now, we will need to check the issue boards to see the changes.
2. Link: Not yet. Good catch. 

Thanks for sharing the gist.
Those changes look great.

**Comment by chachasikes** [comment]
My own feedback is to see (again) if it is possible to comment out the prompts (the "thank you" content) 

This content does not need to live on the completed template, but without it it's a little unwelcoming. 
Adding the `<!-- -->` syntax was also not very user friendly.

**Comment by chachasikes** [comment]
Would love to hear @jaredwyee or @mediajunkie's feedback on it. I wrote it and mostly got "we love it" feedback. We tried the template very early on, and we have learned more since we began. I revised the templates before launch so they were not out of date, but these templates can be considered as features in our layer of support for the design system.

**Comment by mediajunkie** [comment]
defer to @jaredwyee on this
-- 
Christian Crumlish
Product Manager | Office of Digital Innovation
Digital Crisis Standard
<https://github.com/cagov/covid19/wiki/Crisis-Standard> - covid19.ca.gov
415-672-5759 | ***@***.***

Follow us:
web <https://alpha.ca.gov/> | blog <https://medium.com/cadotgov> | twitter
<https://twitter.com/cadotgov>
