### ISSUE TITLE
Components: Make accordions more accessible

### ISSUE THREAD

**Issue by adam-little** [cagov/design-system#712]

**Comment by Courtney-Chittock** [comment]
Issues: 
- Accordion close/open icon is at the far right. Users with a very wide viewport may not see, and users with screen magnifiers may not see. Without the icon, accordions look like styled headings, not like interactable elements.
- There is no "show all/hide all" control to help users who want to see all accordion content.
- Users may associate plus/minus icons with adding and deleting elements, not with toggling an accordion open and closed.

Design notes:
- Played with different icons because the simple minus could be mistaken for part of the text when moved to the left side of the container.
- Added high-contrast stroke on default state to aid visibility (may need to be darker, thicker).
- Added more padding between title/control and edge of container to ease visual tension.
- Focus state should include hover state.
- Added “show all” link for use with multiple accordions. Added icon to increase affordance. (The design for this could be explored more.)
- Removed link color from titles (icon indicator provides guidance that this is an interactable element, and users associate links with navigation, not opening accordions).

**Comment by Courtney-Chittock** [comment]
[View icon explorations](https://www.figma.com/file/Vt2Y8p4mXyzDNqT69KIb6H/Courtney's-Accordion-Sandbox?node-id=0%3A1)
[Prototype 1](https://www.figma.com/proto/Vt2Y8p4mXyzDNqT69KIb6H/Courtney's-Accordion-Sandbox?node-id=16%3A57&scaling=min-zoom&page-id=16%3A56&starting-point-node-id=16%3A57)
[Prototype 2](https://www.figma.com/proto/Vt2Y8p4mXyzDNqT69KIb6H/Courtney's-Accordion-Sandbox?node-id=50%3A118&scaling=min-zoom&page-id=50%3A100&starting-point-node-id=50%3A118)

**Comment by Courtney-Chittock** [comment]
Made some further iterations.
[Final prototype](https://www.figma.com/proto/Vt2Y8p4mXyzDNqT69KIb6H/Courtney's-Accordion-Sandbox?node-id=113%3A809&scaling=min-zoom&page-id=113%3A797&starting-point-node-id=113%3A816)

**Comment by Courtney-Chittock** [comment]
Note: once it's ready to go live, we'll also need to:
- Update[ the documentation](https://designsystem.webstandards.ca.gov/components/accordion/readme/)
- Update the Figma component

**Comment by Courtney-Chittock** [comment]
And interesting article from NNG: [Accordion Icons: Which Signifiers Work Best?](https://www.nngroup.com/articles/accordion-icons/)

**Comment by kkoryaka** [comment]
Applied new design in State Web Template beta staging: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/accordions.html, @Courtney-Chittock has reviewed and approved it. I will update Design System's accordion with this new design in 1.0.8 release.

**Comment by yesenia-gtz** [comment]
@Courtney-Chittock could you work with the engineers to get this into DS?

**Comment by yesenia-gtz** [comment]
@kkoryaka @Angsv can you please work together to get this into the design system in Q4?
