### ISSUE TITLE
Styles: Remove tabindex attributes on site H2s and H3s

### ISSUE THREAD

**Issue by zakiya** [cagov/design-system#736]
I belive we don’t need `tabindex=-1` on H2s and H3s because they are not tabbable.

**Comment by xjensen** [comment]
The `tabindex=-1` on H2s and H3s enables focus in Javascript via `HTMLElement.focus()`. We use `.focus()` in some of our Javascript, most relevantly the page-navigation component. So the opposite may be advisable at the moment; we should probably be using `tabindex=-1` with more headings, in more places. See #661 and #670.

With that said, there might be some opportunity to remove this requirement in a redesign of the page-navigation component. I have a running list of grievances with that component at #672. When we can get rid of the big Safari polyfill for smooth scrolling, we may be able to remove the `.focus()` JS (and therefore the `tabindex=-1` on headings too).

**Comment by xjensen** [comment]
`tabindex=-1` allows focus but not tabbing. It's weird. 

Here's the implication for the current version of page-navigation component. When a reader selects a link in the page-navigation component, we need the browser's focus to shift to the relevant section of the document. If the reader hits tab after selecting a page-navigation link, we want the focus to go to the next link (or whatever tabbable thing) where the reader is actually reading.

Before, the focus would stay in the page-navigation widget. So upon tabbing again, the page focus would shift back up to the next link in the page-navigation component. The whole page would scroll away from where the reader was reading upon hitting tab again. 

We fixed this in #670 by using JS to ensure the focus, or "next focus", would go to the correct part of the page after clicking a page-navigation link. Upon hitting tab again, the page does not shift back up to the page-navigation widget. This is where `tabindex=-1` and `.focus()` play their part.

None of this is necessary on the component pages (like the one in your link) because the page-navigation component isn't on those pages. Pages with the page-navigation component, like the [About page](https://designsystem.webstandards.ca.gov/about/), would be a better example. However, we need to add `tabindex=-1` to headings in the markdown processor for all pages, even those that don't have the page-navigation component. It should be safe, if superfluous.

I agree it's annoying to need to put `tabindex=-1` on all of our headings, and also annoying that we use `.focus()` instead of just relying on the browser's anchor linking. We'd need to rewrite the page-navigation component to overcome the above concerns. I'm on board with addressing this. I'm just trying to say it's more work than meets the eye.
