### ISSUE TITLE
Menu component breaking change: Rewrite menu so it works without javascript

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#741]
The current [menu component ](https://github.com/cagov/design-system/tree/main/components/site-navigation)works correctly when javascript is enabled.

It would be better if it would expand without requiring javascript so that if there was a client side error or the visitor had some browser that was very old and didn't support the required code they could still navigate the site.

In order to create a new version of the menu we can prototype a new version that looks similar to the current one either locally in a branch or totally outside the project on codepen.

Get feedback on the prototype and incorporate it before making a new pull request intp the project

**Comment by zakiya** [comment]
**Acceptance criteria:**
- Navigation should at minimum meet our (accessibility standards)[https://designsystem.webstandards.ca.gov/components/site-navigation/readme/#standard-accessibility-review] 
    - Users should be able to navigate all links using a screen reader
    - Users should be able to navigate all links without a mouse (keyboard only) 
- Navigation should be responsive
    - Responsiveness should work on a window resize, not just on initial page load
- Navigation should be progressively enhanced
     - Users should be able to navigate to all links with javascript disabled. 

This article from a11y Matters is a good example of how one should think through navigation:  https://www.a11ymatters.com/pattern/mobile-nav/

**For discussion**
Our current site navigation component allows for top level items that are not links. I think this is a practice that should be avoided for usability, SEO, and accessibility reasons. At the same time I recognize this is frequently a request from clients. 

@aaronhans @xjensen Free free to add anything you think I may have missed.

**Comment by zakiya** [comment]
Here's an example of a dropdown menu that works without js from my previous gig:
https://www.epihc.org/

Here are the relevant files if you want to get a sense of how it works. But since this was a Drupal site I would not recommend copy/pasting the code.
https://github.com/zakiya/menu-files

**Comment by saldanaj27** [comment]
Hi guys, 

I have been getting more progress done on this issue since our meeting last Friday. I have been able to access the menu without JavaScript while in desktop view using the hover effect. I am cleaning up the CSS code to make sure I have all the CSS changes that were added with JavaScript. Unfortunately, I have been struggling with the mobile view. I believe I found a way to do this but it would have to require structural changes within the HTML code. The HTML structure worked because the JS code was able to reach HTML classes without the need to have them be siblings, parents, or children, but without JS I would have to find a way to attach the "site-header" div class within "cagov-site-navigation" to have the mobile icons along with the menu dropdown. I looked into the EPIHC website that Zakiya shared to find if there is another way, but it seems like they use JavaScript for the mobile view, but not the desktop view

That is where I am at right now and would love to hear some feedback. I think I am getting close with finishing this issue.

**Comment by aaronhans** [comment]
Can consolidate with https://github.com/cagov/design-system/issues/319

**Comment by yesenia-gtz** [comment]
adding to close out #319 

When javascript is disabled on drought and cannabis, many of the pages are not reachable because the main navigation drop downs are generated by javascript. This seems especially an issue on cannabis because the main nav links are dummy links that lead to pages like https://cannabis.ca.gov/about-us/ I think it’s fair to argue that very few users have javascript disabled but this feels like it goes against the way we’ve talked about progressive enhancement.

Possible failure cases:
JavaScript is disabled or not supported
JavaScript is executing but custom elements are not supported
JavaScript is executing but asset failed to load

Possible solutions CSS/HTML only solutions:
https://codepen.io/markcaron/pen/wdVmpB

**Comment by aaronhans** [comment]
Fantastic work on this issue @saldanaj27! Love all the updates in this PR: https://github.com/cagov/design-system/pull/826
