### ISSUE TITLE
Images on homepage above linked titles should be links 

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#764]
Problem:

The sections on the homepage: "What's in the Design System" or "Who's using the Design System", I have to click the respective text or button. It would be nice to be able to click the image/thumbnail too

**Comment by aaronhans** [comment]
Assigning to @adam-little for design review before code changes

**Comment by adam-little** [comment]
Does this apply to any card that has A) a link and B) an image?

If so, then we should also apply this to:

1. Featured principle card on homepage
2. Component cards on [Components landing page](https://designsystem.webstandards.ca.gov/components/)

**Comment by adam-little** [comment]
@aaronhans After discussing with the design team, we suggest making images clickable (per Jared's suggestion) and apply that rule to all cards (except the homepage hero card). 

So that would include the following:
![image](https://user-images.githubusercontent.com/69167298/160706469-19aa5c26-7da3-46a0-9f3d-21ae0a87052f.png)
![image](https://user-images.githubusercontent.com/69167298/160706514-a785e047-3560-46c4-a32e-24a21174504b.png)
![image](https://user-images.githubusercontent.com/69167298/160706542-8e301218-c130-4268-8de6-6e94b70b166c.png)
![image](https://user-images.githubusercontent.com/69167298/160706582-75b29c91-31a8-4e8d-9473-ae162352756a.png)

**Comment by alexhu00** [comment]
On it!

**Comment by yesenia-gtz** [comment]
Hello, checking in on this Will these updates make it into the next release? I am gathering release updates for DWSN share out on April 21

**Comment by aaronhans** [comment]
Yep, great work by @alexhu00 here! We just merged the PR with the fix into the releaes branch: https://github.com/cagov/design-system/pull/774
