### ISSUE TITLE
Bug: anchor links navigate too far above target

### ISSUE THREAD

**Issue by aaronhans** [cagov/design-system#808]
This problem has been reported on the design system site by @ashleydraper and on the development.digital.ca.gov site which uses design system components by Regan.

Noticed in sidebar links all over the design system site by Ashley.

From Regan:

The sidebar jump links seem to calculate a higher y-value than needed (maybe 150px off due to header calculation?). Persists across browsers on Mac/iPhone

**Comment by m-sullivan7** [comment]
This still seems to be an issue. While it jumps to the header, that header is at the bottom of the screen, rather than the top.

**Comment by zakiya** [comment]
@aaronhans @ashleydraper  I couldn't recreate this at any screen size. Could you include the url+path, browser, and the link that was clicked? Bonus points for video screen shot.

**Comment by m-sullivan7** [comment]
@zakiya and @aaronhans I still get this when using Firefox on PC. While I don't have video capture possibilities (at least that I know of with my baseline Windows setup), here's a step-by-step of how I got my bug with screenshots.

1. I go to https://designsystem.webstandards.ca.gov/style/content/.
![image](https://user-images.githubusercontent.com/69169190/181604869-49240b1d-985e-4578-a3d5-2b738ce7997b.png)
2. I click **Our inspiration** in the left menu.
3. It moves the screen slightly so the _Our inspiration_ header is at the bottom of the screen rather than the top.
![image](https://user-images.githubusercontent.com/69169190/181605471-9e01fe58-651c-4cfb-ab8b-5c712116fc50.png)

I'd expect the header to be at the top of the screen rather than the bottom.

Just the observations of a California citizen. 😄

**Comment by xjensen** [comment]
I bet this would be solved by addressing the first bullet point in #672. 

Safari 15.4 has been out for a while now, so we could remove all of that polyfill code and just trust the browser to scroll to the right place.

**Comment by aaronhans** [comment]
Nice @xjensen! I love that solution

**Comment by zakiya** [comment]
Thanks all! Reassigning to @xjensen so @aaronhans can focus on Benefits.

**Comment by xjensen** [comment]
PR is ready in #926.
