### ISSUE TITLE
Patterns: Video content & captioning

### ISSUE THREAD

**Issue by chachasikes** [cagov/design-system#840]
Having a discussion with Wes Breazell from DCC about open and closed captions.

Starting a thread to track this in case it's something we may include in guidance for content creators and web teams.

For cannabis.ca.gov, we have some video content for public information campaigns.

Curious what web standards we have already, and if that guidance needs a refresh with any changes in web standards.

**Comment by chachasikes** [comment]
@kkoryaka Hey Konstantin - we are wondering if this is something you have worked on with any accessible content, and if not, if you know anyone who has.

**Comment by m-sullivan7** [comment]
I've worked a little bit in video captioning at UC San Diego (so state adjacent). We hosted our videos on YouTube. Because these were scripted videos we created, we uploaded text docs with the transcripts. I then manually audited them to make sure the time notes were corrected. This was a while ago (2017 would have been the most recent time I would have done this work), so there may be better options.

YouTube also has automated captioning that you can turn on. Much like Google Translate, the quality can be variable.

I've started to see some mobile ads that have captions built into the video (probably to solve for people for me that have media sound turned off by default) and have even seen it on streaming commercials on services like Hulu. I've been intrigued with putting captions on by default as a way of normalizing them. (I increasingly meet people with hearing who always watch with captions for a host of reasons.)

That's as much as I know on this topic!

**Comment by chachasikes** [comment]
Twitter responses:
* https://twitter.com/adrianogazza/status/1526544248182657024
* https://twitter.com/danachis/status/1526533095477981184

<img width="634" alt="Screen Shot 2022-05-17 at 8 10 15 AM" src="https://user-images.githubusercontent.com/149436/168845535-9c16852a-3fe8-4229-ad9b-89be8b5838b9.png">
<img width="631" alt="Screen Shot 2022-05-17 at 8 10 11 AM" src="https://user-images.githubusercontent.com/149436/168845545-4d2288ae-e998-4140-a58e-dc1d9fb63f92.png">
