### ISSUE TITLE
Bug: Contact form not working

### ISSUE THREAD

**Issue by zakiya** [cagov/design-system#976]
### Urls where issue was found

[designsystem.webstandards.ca.gov](https://designsystem.webstandards.ca.gov/#:~:text=Be%20a%20part%20of%20the%20Design%20System)

[designsystem.webstandards.ca.gov/contact-us](https://designsystem.webstandards.ca.gov/contact-us/)

### Steps to reproduce

Fill out the form and hit submit

### Expected result

Submission appears at https://airtable.com/app4B5KqaCTSHAdCS/tbliV5kSgz7jBnIyT/viwDkwTUo3wZOqYhF?blocks=hide
Emails are sent to Yesenia and Chach.

### Acceptance criteria
- Form is successfully submitted to Airtable
- If possible, create an automated test to catch the issue if the API fails again. 
- I think the emails should go to Yesenia and Jon at this point since Chach is no longer active on this project. 
- The Airtable Base needs some clean up 
- Add information on the contact form to the root-level README so developers don't have to dig for documentation. 
- Stop using Aaron's Airtable API Key since it will stop working February 1st 2024.  [Airtable recommends using OAuth instead](https://community.airtable.com/t5/announcements/new-api-capabilities-now-in-ga-and-upcoming-api-keys-deprecation/ba-p/141824?utm_ID=recM0iZ3vrAE22OYK&utm_campaign=it_ss_api_key_deprecation_notice&utm_content=email_1a-api-key-deprecation-notice&utm_extra5=developer&utm_medium=email&utm_source=lifecycle_team). 

### Optional criteria
- Filter out xss submissions on the server side

CC:
@chachasikes @YeseniaGtz

**Comment by xjensen** [comment]
The form is working again. Aaron's Airtable Personal Access Token was disabled along with his account. Swapping to another Personal Access Token fixed the issue. 

These Airtable Personal Access Tokens will not be depreciated on 2/1/2024; they're removing a different type of API key. Nonetheless, it's still a good idea to migrate to OAuth, as this ticket demonstrates.

The OAuth migration will require some real work. It's a nice little project.

**Comment by zakiya** [comment]
Here's a quote from the email I got about API keys

> The timeline for the Airtable API key deprecation is below:
> 
> February 2023: Provided API Key deprecation notice
> August 1st, 2023: Users will no longer be able to create new API keys
> February 1st, 2024 (next year): Existing API keys cannot be used to access the Airtable API

I'll forward you the whole email @xjensen

**Comment by xjensen** [comment]
Got the email, thanks!

Aaron already did the work to replace the legacy API key with the newly supported Personal Access Token. [I got my info about the Personal Access Tokens at this page](https://support.airtable.com/docs/airtable-api-key-deprecation-notice#:~:text=API%20key%20deprecation%20details%20and%20timeline&text=As%20this%20is%20a%20major,to%20access%20the%20Airtable%20API.). I believe he included this change when he converted the FaaS from Azure to AWS.

It's still a problem though, because his token expired when he left. (No fault of his, of course. Now we know.) So OAuth is still on the table as essential work IMO.

**Comment by zakiya** [comment]
@xjensen Have you had time to work on OAuth? Should I assign to someone else?

**Comment by xjensen** [comment]
@zakiya Nope, haven't worked on OAuth integration of the form.

At this point, I imagine it would be easier to just get a new Personal Access Token from our shared odi-engineering Airtable service account, so that it's not tied to my account. That would alleviate a lot of the concerns I had before about continuity of service.

But happy to look into it if OAuth is still desired.

**Comment by zakiya** [comment]
We removed the contact forms from the design system. Closing.
